#!/bin/zsh

blue=$'%{\e[0;34m%}'
red=$'%{\e[0;31m%}'
green=$'%{\e[0;32m%}'
cyan=$'%{\e[0;36m%}'
white=$'%{\e[0;37m%}'
magenta=$'%{\e[0;35m%}'
yellow=$'%{\e[0;33m%}'
gray=$'%{\e[0;90m%}'

BOLD=$'%{\e[1m%}'

BLUE=$'%{\e[1;34m%}'
RED=$'%{\e[1;31m%}'
GREEN=$'%{\e[1;32m%}'
CYAN=$'%{\e[1;36m%}'
WHITE=$'%{\e[1;37m%}'
MAGENTA=$'%{\e[1;35m%}'
YELLOW=$'%{\e[1;33m%}'
GRAY=$'%{\e[1;90m%}'


NO_COLOR=$'%{\e[0m%}'
no_color=$'%{\e[0m%}'

