#!/bin/zsh

alias mv='nocorrect mv'
alias cp='nocorrect cp'
alias mkdir='nocorrect mkdir'
alias grep=egrep
alias l='ls -l --color=always'
alias ls='ls --color=always'
alias la='ls -a --color=always'
alias lsd='ls -ld *(-/DN)'
alias lsa='ls -ld .*'

alias wget="wget --timeout 10"
alias grep="grep --color=auto"

alias up="sudo pacman -Suy"
alias pacman="pacman-color"

alias ll='ls -ahl --color | more; echo "\e[1;32m --[\e[1;34m Dirs:\e[1;36m `ls -al | egrep \"^drw\" | wc -l` \e[1;32m|\e[1;35m Files: \e[1;31m`ls -al | egrep -v \"^drw\" | grep -v total | wc -l` \e[1;32m]--"'
