#!/bin/zsh


function get_propmpt() {
    echo "%n${WHITE}@%M${BLUE}# ${NO_COLOR}"
}

function get_rprompt() {
    local rprompt="${GRAY}(%~)  [%T]${NO_COLOR}"
    echo $rprompt
}

function set_rprompt() {
    RPROMPT=`get_rprompt`
}

typeset -ga chpwd_functions
chpwd_functions+='set_rprompt'

PROMPT=`get_propmpt`
RPROMPT=`get_rprompt`
