#!/bin/zsh


function get_propmpt() {
    echo "%n${WHITE}@%M${BLUE}# ${NO_COLOR}"
}

function get_rprompt() {
    local rprompt="${GRAY}(%~)  [%T]${NO_COLOR}"
    if [[ -f .git/HEAD ]]
    then
        # a git repository
        rprompt="${GREEN}git:${RED}`git branch | sed -ne 's/^\* \(\S\+\)/\1/p'` $rprompt"
    fi
    echo $rprompt
}

function set_rprompt() {
    RPROMPT=`get_rprompt`
}

typeset -ga chpwd_functions
chpwd_functions+='set_rprompt'

PROMPT=`get_propmpt`
RPROMPT=`get_rprompt`
