#!/bin/sh
exec $(

  echo "chromium --incognito https://google.com
firefox -p google --no-remote  https://gmail.com
firefox -p googlemeet --no-remote  https://meet.google.com
firefox -p confio --no-remote  https://outlook.office.com/mail
" | dmenu

)
