#!/bin/sh

creds=$(gopass ls --flat | rofi -dmenu)
echo "$creds" | rev | cut -d / -f 1 | rev | xdotool type --clearmodifiers --file -
xdotool key Tab
echo "$creds" | xargs --no-run-if-empty gopass show -o | xdotool type --clearmodifiers --file -
